-- ============================================================================
-- 1. CRIAR TABELA DE CONTEÚDO (site_content)
-- Esta tabela armazenará todo o conteúdo textual e estrutura do site (Hero, Pacotes, Galeria) em JSON.
-- ============================================================================

CREATE TABLE public.site_content (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- Inserir o registro inicial (ID 1) vazio ou com dados padrão para garantir que a API encontre algo.
INSERT INTO public.site_content (id, content)
VALUES (1, '{}')
ON CONFLICT (id) DO NOTHING;

-- Habilitar RLS (Row Level Security) - Essencial para segurança e para remover alertas do Supabase
ALTER TABLE public.site_content ENABLE ROW LEVEL SECURITY;

-- Política: Permitir leitura pública (todos podem ver o site)
DROP POLICY IF EXISTS "Public Read Content" ON public.site_content;
CREATE POLICY "Public Read Content" 
ON public.site_content FOR SELECT 
TO public
USING (true);

-- Política: Permitir atualização completa (utilizado pelo admin via app.py)
DROP POLICY IF EXISTS "Allow All Content" ON public.site_content;
CREATE POLICY "Allow All Content" 
ON public.site_content FOR ALL 
TO public
USING (true) 
WITH CHECK (true);


-- ============================================================================
-- 2. CONFIGURAR STORAGE (BUCKET 'images')
-- Este script insere o bucket diretamente. Se preferir, crie pela UI do Supabase: "Storage" -> "New Bucket" -> "images".
-- ============================================================================

-- Tenta criar o bucket 'images' (público)
INSERT INTO storage.buckets (id, name, public)
VALUES ('images', 'images', true)
ON CONFLICT (id) DO NOTHING;

-- Política de Storage: Permitir que QUALQUER UM veja as imagens (Leitura Pública)
CREATE POLICY "Public Access to Images"
ON storage.objects FOR SELECT
USING ( bucket_id = 'images' );

-- Política de Storage: Permitir Upload (Inserção) - Ajuste conforme necessidade de segurança
-- Aqui estamos permitindo upload irrestrito para facilitar. Em produção, restrinja.
CREATE POLICY "Allow Uploads"
ON storage.objects FOR INSERT
WITH CHECK ( bucket_id = 'images' );

-- Política de Storage: Permitir Update/Delete
CREATE POLICY "Allow Updates/Deletes"
ON storage.objects FOR UPDATE
USING ( bucket_id = 'images' );

CREATE POLICY "Allow Deletes"
ON storage.objects FOR DELETE
USING ( bucket_id = 'images' );


-- ============================================================================
-- 3. CONFIGURAR STORAGE PARA VÍDEOS (BUCKET 'videos')
-- ============================================================================

-- Criar o bucket 'videos' (público)
INSERT INTO storage.buckets (id, name, public)
VALUES ('videos', 'videos', true)
ON CONFLICT (id) DO NOTHING;

-- Política de Storage: Permitir que QUALQUER UM veja os vídeos (Leitura Pública)
CREATE POLICY "Public Access to Videos"
ON storage.objects FOR SELECT
USING ( bucket_id = 'videos' );

-- Política de Storage: Permitir Upload de Vídeos
CREATE POLICY "Allow Video Uploads"
ON storage.objects FOR INSERT
WITH CHECK ( bucket_id = 'videos' );

-- Política de Storage: Permitir Update/Delete de Vídeos
CREATE POLICY "Allow Video Updates"
ON storage.objects FOR UPDATE
USING ( bucket_id = 'videos' );

CREATE POLICY "Allow Video Deletes"
ON storage.objects FOR DELETE
USING ( bucket_id = 'videos' );
